title: Is ChatGPT still cool?
description: Be Learners Team! An educational initiative on Artificial Intelligence and Digital Knowledge.
sitename: Chat BLT
author: Be Learners Team
baseurl: ''
github_url: https://github.com/orgs/be-learners-team/discussions/1
twitter_url: https://twitter.com/drzhelnov
linkedin_url: https://www.linkedin.com/feed/update/urn:li:activity:7222153988438118400/
coffee_url: https://ko-fi.com/zheln
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
plugins:
  - jekyll-target-blank
